const apiBaseUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api/v1';
export type PickupLocationStatus = 'ACTIVE' | 'INACTIVE';
export interface PickupLocationRecord { id:string; locationNumber:string; name:string; cityId:string; city:string; region:string; address:string; postalCode:string|null; latitude:number|null; longitude:number|null; status:PickupLocationStatus; updatedBy:string|null; createdAt:string; updatedAt:string; }
export interface PickupLocationInput { name:string; cityId:string; address:string; postalCode:string|null; latitude:number|null; longitude:number|null; status:PickupLocationStatus; }
export class PickupLocationRequestError extends Error { constructor(message:string, public fieldErrors:Record<string,string>={}) { super(message); this.name='PickupLocationRequestError'; } }
export async function listPickupLocations(filters:{page?:number;search?:string;status?:PickupLocationStatus|''}={}) { const params=new URLSearchParams({page:String(filters.page??1)}); if(filters.search)params.set('search',filters.search); if(filters.status)params.set('status',filters.status); return (await request<{success:true;data:{items:PickupLocationRecord[];pagination:{page:number;pageSize:number;total:number;totalPages:number}}}>(`/admin/pickup-locations?${params}`)).data; }
export async function getPickupLocation(id:string) { return (await request<{success:true;data:{location:PickupLocationRecord}}>(`/admin/pickup-locations/${encodeURIComponent(id)}`)).data.location; }
export async function createPickupLocation(input:PickupLocationInput) { return (await request<{success:true;data:{location:PickupLocationRecord}}>('/admin/pickup-locations',{method:'POST',body:JSON.stringify(input)})).data.location; }
export async function updatePickupLocation(id:string,input:PickupLocationInput) { return (await request<{success:true;data:{location:PickupLocationRecord}}>(`/admin/pickup-locations/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(input)})).data.location; }
async function request<T>(path:string,options:RequestInit={}) { let response:Response; try { response=await fetch(`${apiBaseUrl}${path}`,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers??{})}}); } catch { throw new PickupLocationRequestError('Unable to connect to the pickup-location service.'); } const body=await response.json().catch(()=>({})) as T & {message?:string;errors?:Record<string,string>;error?:{message?:string;errors?:Record<string,string>}}; if(!response.ok) throw new PickupLocationRequestError(body.error?.message??body.message??'Unable to complete the request.',body.error?.errors??body.errors??{}); return body as T; }
