import { NativeTomSelect } from '../../components/ui/NativeTomSelect';
import { MapPin, Pencil, Plus, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { listPickupLocations, type PickupLocationRecord, type PickupLocationStatus } from '../../services/pickupLocationsService';

export function AdminPickupLocations() {
  const navigate=useNavigate(); const [page,setPage]=useState(1); const [search,setSearch]=useState(''); const [status,setStatus]=useState<PickupLocationStatus|''>(''); const [items,setItems]=useState<PickupLocationRecord[]>([]); const [pagination,setPagination]=useState({page:1,pageSize:10,total:0,totalPages:1}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const result=await listPickupLocations({page,search,status});setItems(result.items);setPagination(result.pagination);}catch{setError('Unable to load pickup locations.');}finally{setLoading(false);}};
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer);},[page,search,status]);
  return <div className="mx-auto max-w-[1500px] space-y-4">
    <div className="customer-secondary text-sm"><Link to="/admin/pickup-locations" className="hover:text-[var(--customer-primary)]">Administration</Link><span className="mx-2">/</span><span className="customer-text">Pickup-from Locations</span></div>
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="customer-text text-2xl font-bold">Pickup-from Locations</h1><p className="customer-secondary mt-1 text-sm">Manage approved plant and depot locations used for customer pick-up.</p></div><Link to="/admin/pickup-locations/create" className="customer-primary-bg inline-flex h-10 items-center gap-2 rounded-lg px-4 text-sm font-semibold text-white"><Plus size={16}/>New Pickup Location</Link></header>
    <section className="customer-card overflow-hidden rounded-xl border shadow-sm">
      <div className="customer-border-soft flex flex-wrap items-center justify-between gap-3 border-b p-4"><label className="relative w-full max-w-sm"><Search size={17} className="customer-muted absolute left-3 top-2.5"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search locations" className="customer-input h-10 w-full rounded-lg border pl-9 pr-3 text-sm"/></label><div className="flex items-center gap-3"><NativeTomSelect value={status} onChange={e=>{setStatus(e.target.value as PickupLocationStatus|'');setPage(1)}} className="customer-input h-10 rounded-lg border px-3 text-sm"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></NativeTomSelect><span className="customer-secondary text-sm">{pagination.total} locations</span></div></div>
      {error&&<div className="m-4 flex justify-between rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-[#b42318]"><span>{error}</span><button onClick={()=>void load()} className="font-semibold">Retry</button></div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="customer-surface-secondary customer-secondary text-xs uppercase"><tr><th className="px-4 py-3"><input type="checkbox" aria-label="Select visible locations"/></th><th className="px-4 py-3">S.No.</th><th className="px-4 py-3">Location ID</th><th className="px-4 py-3">Name</th><th className="px-4 py-3">City</th><th className="px-4 py-3">Address</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last Updated</th><th className="px-4 py-3">Updated By</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{loading?Array.from({length:4}).map((_,i)=><tr key={i} className="customer-border-soft border-t"><td colSpan={10} className="px-4 py-4"><div className="customer-surface-secondary h-5 animate-pulse rounded"/></td></tr>):items.map((item,index)=><tr key={item.id} className="customer-border-soft border-t transition hover:bg-[var(--customer-surface-secondary)]"><td className="px-4 py-3"><input type="checkbox" aria-label={`Select ${item.name}`}/></td><td className="px-4 py-3">{(page-1)*10+index+1}</td><td className="px-4 py-3 font-semibold">{item.locationNumber}</td><td className="px-4 py-3"><button onClick={()=>navigate(`/admin/pickup-locations/${item.id}`)} className="font-semibold text-[var(--customer-primary)] hover:underline">{item.name}</button></td><td className="px-4 py-3">{item.city}</td><td className="max-w-[280px] truncate px-4 py-3" title={item.address}>{item.address}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${item.status==='ACTIVE'?'bg-emerald-500':'bg-slate-400'}`}/>{item.status==='ACTIVE'?'Active':'Inactive'}</span></td><td className="px-4 py-3" title={new Date(item.updatedAt).toLocaleString()}>{relative(item.updatedAt)}</td><td className="px-4 py-3">{item.updatedBy??'Not provided'}</td><td className="px-4 py-3"><button onClick={()=>navigate(`/admin/pickup-locations/${item.id}`)} className="customer-border customer-secondary inline-flex rounded-lg border p-2 hover:text-[var(--customer-primary)]" aria-label={`Edit ${item.name}`}><Pencil size={15}/></button></td></tr>)}</tbody></table></div>
      {!loading&&!items.length&&<div className="flex flex-col items-center p-10 text-center"><MapPin className="customer-muted"/><p className="customer-text mt-3 font-semibold">No pickup locations found</p><p className="customer-secondary mt-1 text-sm">Create the first approved pickup location.</p></div>}
      <div className="customer-border-soft flex items-center justify-between border-t p-4 text-sm"><span className="customer-secondary">Showing {pagination.total?((page-1)*10)+1:0}â€“{Math.min(page*10,pagination.total)} of {pagination.total}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="customer-border rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={page>=pagination.totalPages} onClick={()=>setPage(v=>v+1)} className="customer-border rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div>
    </section>
  </div>;
}
function relative(value:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return seconds<10?'Just now':`${seconds} seconds ago`;const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes} minute${minutes===1?'':'s'} ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} hour${hours===1?'':'s'} ago`;const days=Math.floor(hours/24);return days===1?'Yesterday':`${days} days ago`;}
